#pragma once

#define IDR_MAINMENU 1
#define IDR_VISUAL_STYLES_MANIFEST 2
#define IDR_MAINACCEL 180
#define IDI_REVERSI 3
#define IDC_REVERSI_CROSS 103

#define IDM_PASS 20
#define IDM_NEW 25
#define IDM_HELP_CONTENTS 30
#define IDM_HELP_SEARCH 31
#define IDM_HELP_USING 32
#define IDM_ABOUT 33
#define IDM_BEGINNER 41
#define IDM_INTERMEDIATE 42
#define IDM_EXPERT 44
#define IDM_MASTER 46
#define IDM_HINT 50
#define IDM_EXIT 52
#define IDM_ANIM_NONE 80
#define IDM_ANIM_SLOW 81
#define IDM_ANIM_FAST 82

#define IDS_APP_TITLE 3
#define IDS_PRACTICE_TITLE 4
#define IDS_PASS_TEXT 5
#define IDS_MUST_PASS 6
#define IDS_DRAW 7
#define IDS_LOST_FMT 8
#define IDS_WON_FMT 9
#define IDS_ABOUT_MENU 10
#define IDS_INVALID_MOVE 13
#define IDS_CANNOT_PASS 14
#define IDS_HELP_FILE 15
#define IDS_INI_FILE 20
#define IDS_PROFILE_APP 25
#define IDS_ANIMATION_KEY 30
#define IDS_SKILL_KEY 35
#define IDS_HELP_CONTENTS_TEXT 100
#define IDS_HELP_SEARCH_TEXT 101
#define IDS_HELP_USING_TEXT 102
#define IDS_ABOUT_TEXT 103
#define IDS_REGISTER_FAIL 104
#define IDS_CREATE_FAIL 105
#define IDS_FILE_DESCRIPTION 106
#define IDS_ORIGINAL_FILENAME 107
#define IDS_HELP_TITLE 108
